---
- name: Install the nginx server
  apt:
    name: nginx
  notify:
    - Restart Nginx

- name: Configure the proxied services
  template:
    src: site.conf
    dest: "/etc/nginx/sites-enabled/{{ service.domain }}.conf"
  loop: "{{ proxied_services }}"
  loop_control:
    loop_var: service
  notify:
    - Restart Nginx

- name: Add the service domain to the /etc/hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ intranet_ip }}  {{ service.domain }}.{{ domain }}"
  loop: "{{ proxied_services }}"
  loop_control:
    loop_var: service
