---
- name: Check if users ~{{ user }}/.pki/nssdb exists
  command: certutil -L -d sql:/home/{{ user }}/.pki/nssdb
  register: nssdb_exists_user
  changed_when: false
  failed_when: false

- name: Check if users ~{{ user }}/.pki/nssdb folder is there
  stat:
    path: "/home/{{ user }}/.pki/nssdb"
  register: nssdb_stat_user
  when: nssdb_exists_user.rc != 0

- name: Create users ~{{ user }}/.pki/nssdb folder
  file:
    path: "/home/{{ user }}/.pki/nssdb"
    state: directory
  register: nssdb_folder_created_user
  when: nssdb_stat_user is defined and nssdb_stat_user.stat is defined and nssdb_stat_user.stat.exists == false

- name: Initialize db in users ~{{ user }}/.pki/nssdb
  command: certutil -N -d sql:/home/{{ user }}/.pki/nssdb --empty-password
  when: nssdb_folder_created_user.changed

- name: Install certificates to users ~{{ user }}/.pki/nssdb
  command: >
    certutil -A -d "sql:/home/{{ user }}/.pki/nssdb"
    -n "{{ root_ca_certificate.name }}"
    -t "CT,c,c"
    -i "{{ root_ca_certificate.path }}"
  changed_when: false

- name: Get the firefox profiles
  find:
    file_type: directory
    paths: "/home/{{ user }}/.mozilla/firefox"
    patterns: "*.default*"
  register: firefox_profiles

- name: Install certificates to users ~{{ user }}/.pki/nssdb
  command: >
    certutil -A -d "{{ profile.path }}"
    -n "{{ root_ca_certificate.name }}"
    -t "Cu,Cuw,Tuw"
    -i "{{ root_ca_certificate.path }}"
  loop: "{{ firefox_profiles.files }}"
  loop_control:
    loop_var: profile
  notify: Update LTSP initrd
