network:
  version: 2
  renderer: networkd
  ethernets:
    {% if intranet_interface is defined %}
    {{- intranet_interface -}}:
      dhcp4: false
      dhcp6: false
      optional: true
      addresses:
        - {{ intranet_ip }}/24
{% endif %}
    {% if internet_interface is defined %}
    {{- internet_interface -}}:
      dhcp4: true
      dhcp6: false
      optional: true
{% endif %}
