- name: Install server
  hosts: server
  become: yes
  roles:
    - geerlingguy.security
    - geerlingguy.docker
    - desktop
    - role: netplan
      tags:
        - netplan
    - role: users
      tags:
        - users
    - name: ansible
      tags:
        - light-client
    - name: ltsp
      tags:
        - ltsp
    - name: ssl
      tags:
        - webserver
        - ssl
    - role: epoptes
      tags:
        - light-client
    - name: chroot
      tags:
        - light-client
    - role: configure-ltsp
      tags:
        - configure-ltsp
        - ltsp
    - role: dnsmasq
      tags:
        - webserver
        - dhcp
    - role: nfs
      tags:
        - nfs
    - role: nginx
      tags:
        - webserver
    - role: mysql-server
      tags:
        - webserver
    - role: postfix
      tags:
        - mail
    - role: gitlab
      tags:
        - gitlab
    - role: dev-tools
    - role: certificates-in-browsers
      tags:
        - ssl
