- name: Install chroot
  hosts: chroot
  become: yes
  roles:
    - role: linux-kernel
      tags:
        - lite
    - role: hostname
      tags:
        - lite
    - ssl
    - role: ltsp
      tags:
        - lite
    - role: desktop
      tags:
        - desktop
    - role: dev-tools
      tags:
        - dev-tools
    - role: epoptes
      tags:
        - epoptes
