- name: Install server
  hosts: server
  become: yes
  roles:
    - geerlingguy.security
    - geerlingguy.docker
    - desktop
    - name: ansible
      tags:
        - light-client
    - name: ltsp
      tags:
        - ltsp
    - name: chroot
      tags:
        - light-client
    - role: configure-ltsp
      tags:
        - configure-ltsp
        - ltsp
    - role: dnsmasq
      tags:
        - webserver
        - dhcp
    - role: nfs
      tags:
        - nfs
    - role: netplan
      tags:
        - netplan
    - role: nginx
      tags:
        - webserver
    - role: mysql-server
      tags:
        - webserver
    - role: epoptes
      tags:
        - light-client
