- name: Install server
  hosts: server
  become: yes
  roles:
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: desktop
      tags:
        - desktop
    - role: netplan
      tags:
        - netplan
        - lite
    - role: users
      tags:
        - users
        - lite
    - name: ansible
      tags:
        - light-client
        - lite
        - always
    - name: ltsp
      tags:
        - ltsp
        - lite
    - name: ssl
      tags:
        - webserver
        - ssl
    - role: epoptes
      tags:
        - light-client
        - lite
    - name: chroot
      tags:
        - light-client
        - lite
        - always
    - role: configure-ltsp
      tags:
        - configure-ltsp
        - ltsp
        - lite
    - role: dnsmasq
      tags:
        - webserver
        - dnsmasq
        - lite
    - role: nfs
      tags:
        - nfs
        - lite
    - role: nginx
      tags:
        - webserver
    - role: mysql-server
      tags:
        - webserver
    - role: postfix
      tags:
        - mail
    - role: gitlab
      tags:
        - gitlab
    - role: dev-tools
      tags:
        - dev-tools
    - role: certificates-in-browsers
      tags:
        - ssl
