- name: Install server
  hosts: server
  become: yes
  roles:
    - geerlingguy.security
    - geerlingguy.docker
    - desktop
    - ansible
    - ltsp
    - chroot
    - configure-ltsp
    - dnsmasq
    - nfs
    - role: netplan
      tags: netplan
