---
- name: Install the debootstrap package
  apt:
    name: debootstrap

- name: Make sure the /srv/ltsp directory exists
  file:
    path: /srv/ltsp
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Bootstrap the chroot
  command: debootstrap jammy /srv/ltsp/jammy
  args:
    creates: /srv/ltsp/jammy/etc/lsb-release

- name: Execute chroot ansible playbook
  command: ansible-playbook -i chroot_inventory playbook-chroot.yaml
  args:
    chdir: "{{ provisioning_path }}"
  register: chroot_playbook

- name: Print out chroot playbook output
  debug:
    msg: "{{ chroot_playbook.stdout }}"
