---
- name: Install the debootstrap package
  apt:
    name: debootstrap

- name: Make sure the /srv/ltsp directory exists
  file:
    path: /srv/ltsp
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Bootstrap the chroot
  command: debootstrap jammy /srv/ltsp/jammy
  args:
    creates: /srv/ltsp/jammy/etc/lsb-release

- name: Do the mounts into chroot
  mount:
    path: "/srv/ltsp/jammy{{ item }}"
    src: "{{ item }}"
    fstype: none
    opts: bind
    state: mounted
  loop:
    - /dev
    - /proc
    - /sys

- name: Execute chroot ansible playbook
  command: "ansible-playbook -i chroot_inventory --tags {{ ansible_run_tags | join(',') }} playbook-chroot.yaml"
  args:
    chdir: "{{ provisioning_path }}"
  register: chroot_playbook
  changed_when: chroot_playbook.stdout  is regex("changed=([1-9][0-9]*)")
  notify:
    - Update LTSP client

- name: Print out chroot playbook output
  debug:
    msg: "{{ chroot_playbook.stdout }}"
  changed_when: chroot_playbook.changed
