---
- name: Make sure the netplan config directory exists
  file:
    path: /etc/netplan
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Check configuration
  debug:
    msg: Please define the `network_interfaces` variable in the group_vars/all/network.yaml file
  failed_when: network_interfaces is not defined
  when: network_interfaces is not defined

- name: List all config files in the directory
  find:
    paths: /etc/netplan
    patterns: '*.yaml'
  register: netplan_files

- name: Remove any other netplan config
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ netplan_files.files }}"
  when: item.path != '/etc/netplan/01-netcfg.yaml'
  notify:
    - Apply netplan config

- name: Remove any other netplan config
  file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent
  notify:
    - Apply netplan config

- name: Copy the netplan config file template
  template:
    src: 01-netcfg.yaml
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0644
  notify:
    - Apply netplan config

- name: Flush handlers
  meta: flush_handlers
