---
- name: Create the dev group
  group:
    name: "{{ ansible_common_remote_group }}"
    state: present

- name: Create the student users
  user:
    name: "{{ student }}"
    shell: /bin/bash
    groups: "{{ ansible_common_remote_group }}"
    append: yes
  loop: "{{ students }}"
  loop_control:
    loop_var: student

- name: Add the ansible user to the dev group
  user:
    name: "{{ ansible_user }}"
    groups: "{{ ansible_common_remote_group }}"
    append: yes
