function updateGlitch() {
	
	gType = document.getElementById("glitch-type").value;
	gBG = document.getElementById("bg-color").value;
	gFontSize = document.getElementById("font-size").innerHTML + "px";
	gTextColor = document.getElementById("text-color").value;
	gColor1 = document.getElementById("color1").value;
	gColor2 = document.getElementById("color2").value;
	gText = document.getElementById("text").value;
	
	document.getElementById("glitch").innerHTML = gText;
	document.getElementById("glitch").setAttribute("data-text", gText); 
	document.getElementsByClassName("dm1")[0].style.background = gBG;
	document.getElementsByClassName("glitch-wrapper")[0].style.background = gBG;
	
	this.css = '.glitch-wrapper {\n';
	this.css += '   width: 100%;\n';
	this.css += '   height: 100%;\n';
	this.css += '   display: flex;\n';
	this.css += '   align-items: center;\n';
	this.css += '   justify-content: center;\n';
	this.css += '   text-align: center;\n';
	this.css += '   background-color: ' + gBG + ';\n';
	this.css += '}\n';
	this.css += '\n';
	this.css += '.glitch {\n';
	this.css += '   position: relative;\n';
	this.css += '   font-size: ' + gFontSize + ';\n';
	this.css += '   font-weight: bold;\n';
	this.css += '   color: ' + gTextColor + ';\n';
	this.css += '   letter-spacing: 3px;\n';
if (gType == "transform") {
	this.css += '   animation: shift 4s ease-in-out infinite alternate;\n';
	this.css += '   transform: skewX(0deg);\n';
	this.css += '   z-index: 1;\n';
	this.css += '}\n';
}else{	
	this.css += '   z-index: 1;\n';
	this.css += '}\n';
}
	this.css += '\n';
if (gType == "color"){
	document.getElementById("col1").classList.remove("d-none");
	document.getElementById("col2").classList.remove("d-none");
	this.css += '.glitch:before,\n';
	this.css += '.glitch:after {\n';
	this.css += '   display: block;\n';
	this.css += '   content: attr(data-text);\n';
	this.css += '   position: absolute;\n';
	this.css += '   top: 0;\n';
	this.css += '   left: 0;\n';
	this.css += '   opacity: 0.8;\n';
	this.css += '}\n';
	this.css += '\n';
	this.css += '.glitch:before {\n';
	this.css += '   animation: glitch-it 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94) both infinite;\n';
	this.css += '   color: ' + gColor1 + ';\n';
	this.css += '   z-index: -1;\n';
	this.css += '}\n';
	this.css += '\n';
	this.css += '.glitch:after {\n';
	this.css += '   animation: glitch-it 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94) reverse both infinite;\n';
	this.css += '   color: ' + gColor2 + ';\n';
	this.css += '   z-index: -2;\n';
	this.css += '}\n';
	this.css += '\n';
	this.css += '@keyframes glitch-it {\n';
	this.css += '   0% {\n';
	this.css += '      transform: translate(0);\n';
	this.css += '   }\n';
	this.css += '   20% {\n';
	this.css += '      transform: translate(-2px, 2px);\n';
	this.css += '   }\n';
	this.css += '   40% {\n';
	this.css += '      transform: translate(-2px, -2px);\n';
	this.css += '   }\n';
	this.css += '   60% {\n';
	this.css += '      transform: translate(2px, 2px);\n';
	this.css += '   }\n';
	this.css += '   80% {\n';
	this.css += '      transform: translate(2px, -2px);\n';
	this.css += '   }\n';
	this.css += '   to {\n';
	this.css += '      transform: translate(0);\n';
	this.css += '   }\n';
	this.css += '}';
}else if (gType == "noise") {
	document.getElementById("col1").classList.add("d-none");
	document.getElementById("col2").classList.add("d-none");
	this.css += '.glitch:before {\n';
	this.css += '   content: attr(data-text);\n';
	this.css += '   position: absolute;\n';
	this.css += '   top: 0;\n';
	this.css += '   left: -2px;\n';
	this.css += '   width: 100%;\n';
	this.css += '   color: ' + gFontSize + ';\n';
	this.css += '   background-color: ' + gBG + ';\n';
	this.css += '   overflow: hidden;\n';
	this.css += '   clip: rect(0, 900px, 0, 0);\n';
	this.css += '   animation: noise-before 3s infinite linear alternate-reverse;\n';
	this.css += '}\n';
	this.css += '\n';
	this.css += '.glitch:after {\n';
	this.css += '   content: attr(data-text);\n';
	this.css += '   position: absolute;\n';
	this.css += '   top: 0;\n';
	this.css += '   left: 2px;\n';
	this.css += '   width: 100%;\n';
	this.css += '   color: ' + gFontSize + ';\n';
	this.css += '   background-color: ' + gBG + ';\n';
	this.css += '   overflow: hidden;\n';
	this.css += '   clip: rect(0, 900px, 0, 0);\n';
	this.css += '   animation: noise-after 2s infinite linear alternate-reverse;\n';
	this.css += '}\n';
	this.css += '\n';
	this.css += '@keyframes noise-before {\n';
	this.css += '   0% {\n';
	this.css += '      clip: rect(61px, 9999px, 52px, 0);\n';
	this.css += '   }\n';
	this.css += '   5% {\n';
	this.css += '      clip: rect(33px, 9999px, 144px, 0);\n';
	this.css += '   }\n';
	this.css += '   10% {\n';
	this.css += '      clip: rect(121px, 9999px, 115px, 0);\n';
	this.css += '   }\n';
	this.css += '   15% {\n';
	this.css += '      clip: rect(144px, 9999px, 162px, 0);\n';
	this.css += '   }\n';
	this.css += '   20% {\n';
	this.css += '      clip: rect(62px, 9999px, 180px, 0);\n';
	this.css += '   }\n';
	this.css += '   25% {\n';
	this.css += '      clip: rect(34px, 9999px, 42px, 0);\n';
	this.css += '   }\n';
	this.css += '   30% {\n';
	this.css += '      clip: rect(147px, 9999px, 179px, 0);\n';
	this.css += '   }\n';
	this.css += '   35% {\n';
	this.css += '      clip: rect(99px, 9999px, 63px, 0);\n';
	this.css += '   }\n';
	this.css += '   40% {\n';
	this.css += '      clip: rect(188px, 9999px, 122px, 0);\n';
	this.css += '   }\n';
	this.css += '   45% {\n';
	this.css += '      clip: rect(154px, 9999px, 14px, 0);\n';
	this.css += '   }\n';
	this.css += '   50% {\n';
	this.css += '      clip: rect(63px, 9999px, 37px, 0);\n';
	this.css += '   }\n';
	this.css += '   55% {\n';
	this.css += '      clip: rect(161px, 9999px, 147px, 0);\n';
	this.css += '   }\n';
	this.css += '   60% {\n';
	this.css += '      clip: rect(109px, 9999px, 175px, 0);\n';
	this.css += '   }\n';
	this.css += '   65% {\n';
	this.css += '      clip: rect(157px, 9999px, 88px, 0);\n';
	this.css += '   }\n';
	this.css += '   70% {\n';
	this.css += '      clip: rect(173px, 9999px, 131px, 0);\n';
	this.css += '   }\n';
	this.css += '   75% {\n';
	this.css += '      clip: rect(62px, 9999px, 70px, 0);\n';
	this.css += '   }\n';
	this.css += '   80% {\n';
	this.css += '      clip: rect(24px, 9999px, 153px, 0);\n';
	this.css += '   }\n';
	this.css += '   85% {\n';
	this.css += '      clip: rect(138px, 9999px, 40px, 0);\n';
	this.css += '   }\n';
	this.css += '   90% {\n';
	this.css += '      clip: rect(79px, 9999px, 136px, 0);\n';
	this.css += '   }\n';
	this.css += '   95% {\n';
	this.css += '      clip: rect(25px, 9999px, 34px, 0);\n';
	this.css += '   }\n';
	this.css += '   100% {\n';
	this.css += '      clip: rect(173px, 9999px, 166px, 0);\n';
	this.css += '   }\n';
	this.css += '}\n';
	this.css += '\n';
	this.css += '@keyframes noise-after {\n';
	this.css += '   0% {\n';
	this.css += '      clip: rect(26px, 9999px, 33px, 0);\n';
	this.css += '   }\n';
	this.css += '   5% {\n';
	this.css += '      clip: rect(140px, 9999px, 198px, 0);\n';
	this.css += '   }\n';
	this.css += '   10% {\n';
	this.css += '      clip: rect(184px, 9999px, 89px, 0);\n';
	this.css += '   }\n';
	this.css += '   15% {\n';
	this.css += '      clip: rect(121px, 9999px, 6px, 0);\n';
	this.css += '   }\n';
	this.css += '   20% {\n';
	this.css += '      clip: rect(181px, 9999px, 99px, 0);\n';
	this.css += '   }\n';
	this.css += '   25% {\n';
	this.css += '      clip: rect(154px, 9999px, 133px, 0);\n';
	this.css += '   }\n';
	this.css += '   30% {\n';
	this.css += '      clip: rect(134px, 9999px, 169px, 0);\n';
	this.css += '   }\n';
	this.css += '   35% {\n';
	this.css += '      clip: rect(26px, 9999px, 187px, 0);\n';
	this.css += '   }\n';
	this.css += '   40% {\n';
	this.css += '      clip: rect(147px, 9999px, 137px, 0);\n';
	this.css += '   }\n';
	this.css += '   45% {\n';
	this.css += '      clip: rect(31px, 9999px, 52px, 0);\n';
	this.css += '   }\n';
	this.css += '   50% {\n';
	this.css += '      clip: rect(191px, 9999px, 109px, 0);\n';
	this.css += '   }\n';
	this.css += '   55% {\n';
	this.css += '      clip: rect(74px, 9999px, 54px, 0);\n';
	this.css += '   }\n';
	this.css += '   60% {\n';
	this.css += '      clip: rect(145px, 9999px, 75px, 0);\n';
	this.css += '   }\n';
	this.css += '   65% {\n';
	this.css += '      clip: rect(153px, 9999px, 198px, 0);\n';
	this.css += '   }\n';
	this.css += '   70% {\n';
	this.css += '      clip: rect(99px, 9999px, 136px, 0);\n';
	this.css += '   }\n';
	this.css += '   75% {\n';
	this.css += '      clip: rect(118px, 9999px, 192px, 0);\n';
	this.css += '   }\n';
	this.css += '   80% {\n';
	this.css += '      clip: rect(1px, 9999px, 83px, 0);\n';
	this.css += '   }\n';
	this.css += '   85% {\n';
	this.css += '      clip: rect(145px, 9999px, 98px, 0);\n';
	this.css += '   }\n';
	this.css += '   90% {\n';
	this.css += '      clip: rect(121px, 9999px, 154px, 0);\n';
	this.css += '   }\n';
	this.css += '   95% {\n';
	this.css += '      clip: rect(156px, 9999px, 44px, 0);\n';
	this.css += '   }\n';
	this.css += '   100% {\n';
	this.css += '      clip: rect(67px, 9999px, 122px, 0);\n';
	this.css += '   }\n';
	this.css += '}\n';
}else{
	document.getElementById("col1").classList.add("d-none");
	document.getElementById("col2").classList.add("d-none");
	this.css += '@keyframes shift {\n';
	this.css += '   0%, 40%, 44%, 58%, 61%, 65%, 69%, 73%, 100% {\n';
	this.css += '      transform: skewX(0deg);\n';
	this.css += '   }\n';
	this.css += '   41% {\n';
	this.css += '      transform: skewX(10deg);\n';
	this.css += '   }\n';
	this.css += '   42% {\n';
	this.css += '      transform: skewX(-10deg);\n';
	this.css += '   }\n';
	this.css += '   59% {\n';
	this.css += '      transform: skewX(35deg) skewY(10deg);\n';
	this.css += '   }\n';
	this.css += '   60% {\n';
	this.css += '      transform: skewX(-35deg) skewY(-10deg);\n';
	this.css += '   }\n';
	this.css += '   63% {\n';
	this.css += '      transform: skewX(10deg) skewY(-5deg);\n';
	this.css += '   }\n';
	this.css += '   70% {\n';
	this.css += '      transform: skewX(-30deg) skewY(-20deg);\n';
	this.css += '   }\n';
	this.css += '   71% {\n';
	this.css += '      transform: skewX(10deg) skewY(-10deg);\n';
	this.css += '   }\n';
	this.css += '}\n';	
}

	
	this.html = '<div class="glitch-wrapper">\n';
	this.html += '   <div class="glitch" data-text="' + gText + '">' + gText + '</div>\n';
	this.html += '</div>';

	codeDiv = document.getElementById("code");
	codeHTMLDiv = document.getElementById("code-html");	

	codeDiv.textContent=this.css;
	codeHTMLDiv.textContent=this.html;
	Prism.highlightAll();

	$('style').remove();
	$('head').append('<style type="text/css">' + this.css + '</style>');
	return this.css;	
	
}
var rangeSlider = function(){
  var slider = $('.range-slider'),
      range = $('.form-range');
    
  slider.each(function(){
    range.on('input', function(){
	  var range__input = $(this).data('key');
      $('#'+range__input).html(this.value);
	  updateGlitch();
    });
  });
};

rangeSlider();

window.onload=updateGlitch;