---
- name: Install pip
  apt:
    name: python3-pip

- name: Install Ansible with pip
  pip:
    name: ansible

- name: Make sure provisioning_path exists
  file:
    path: "{{ provisioning_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy provisioning repository to server
  copy:
    src: "{{ playbook_dir }}/{{ item }}"
    dest: "{{ provisioning_path }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - group_vars/
    - roles/linux-kernel/
    - roles/hostname/
    - roles/ltsp/
    - roles/desktop/
    - roles/dev-tools/
    - roles/epoptes/
    - roles/ssl/
    - ansible.cfg
    - chroot_inventory
    - playbook-chroot.yaml
