---
- name: Install the recommended packages
  apt:
    name:
      - ltsp-binaries
      - dnsmasq
      - nfs-kernel-server
      - squashfs-tools
      - ethtool
      - net-tools
      - epoptes
    install_recommends: yes

- name: Add epoptes to the administrator group
  user:
    name: epoptes
    groups: "{{ ansible_user }}"
    append: yes

- name: Create the image
  command: ltsp image jammy
  args:
    creates: /srv/ltsp/images/jammy.img
  notify:
    - Update LTFS initrd

- name: Create the ipxe
  command: ltsp ipxe
  args:
    creates: /srv/tftp/ltsp/ltsp.ipxe
  notify:
    - Update LTFS initrd

- name: Make sure the /etc/ltsp/bin directory exists
  file:
    path: /etc/ltsp/bin
    state: directory
    owner: root
    group: root
    mode: 0755
  notify:
    - Update LTFS initrd

- name: Copy the sshfs file
  copy:
    src: /usr/bin/sshfs
    dest: /etc/ltsp/bin/sshfs-x86_64
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  notify:
    - Update LTFS initrd
