---
- name: Install the recommended packages
  apt:
    name:
      - ltsp-binaries
      - dnsmasq
      - nfs-kernel-server
      - squashfs-tools
      - ethtool
      - net-tools
      - epoptes
    install_recommends: yes

- name: Add epoptes to the administrator group
  user:
    name: epoptes
    groups: "{{ ansible_user }}"
    append: yes

- name: Copy the ltsp.conf file template
  template:
    src: ltsp.conf
    dest: /etc/ltsp/ltsp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Update LTSP initrd
