---
- name: Instal software-properties-common
  apt:
    name: software-properties-common
    install_recommends: yes

- name: Add the LTSP PPA repository
  apt_repository:
    repo: ppa:ltsp

- name: Install the ltsp package
  apt:
    name:
      - ltsp
