---
- name: Install basic packages
  apt:
    name:
      - vim
      - git
      - curl
      - wget
      - net-tools
      - dnsutils
      - build-essential
      - php

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Add the Mozilla PPA repository
  block:
    - apt_repository:
        repo: ppa:mozillateam/ppa
    - template:
        src: mozillateamppa
        dest: /etc/apt/preferences.d/mozillateamppa
    - template:
        src: 51unattended-upgrades-firefox
        dest: /etc/apt/apt.conf.d/51unattended-upgrades-firefox
  notify:
    - Update apt cache

- name: Add the Google Chrome repository
  block:
    - get_url:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        dest: /etc/apt/keyrings/chrome.asc
    - apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/chrome.asc] http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome

- name: Add the Microsoft repository
  block:
    - get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/keyrings/microsoft.asc
    - apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main
        filename: vscode

- name: Add the Inkscape PPA repository
  apt_repository:
    repo: ppa:inkscape.dev/stable

- name: Add the Sublime text repository
  block:
    - get_url:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        dest: /etc/apt/keyrings/sublime.asc
    - apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/sublime.asc] https://download.sublimetext.com/ apt/stable/
        filename: sublime-text

- name: Add the Typora repository
  block:
    - get_url:
        url: https://typoraio.cn/linux/public-key.asc
        dest: /etc/apt/keyrings/typora.asc
    - apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/typora.asc] https://typora.io/linux ./
        filename: typora

- name: Add Yarn repository
  block:
    - get_url:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        dest: /etc/apt/keyrings/yarn.asc
    - apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/yarn.asc] https://dl.yarnpkg.com/debian/ stable main
        filename: yarn

- name: Add TablePlus repository
  block:
    - name: Add the TablePlus gpg key
      get_url:
        url: https://deb.tableplus.com/apt.tableplus.com.gpg.key
        dest: /etc/apt/keyrings/tableplus.asc
    - name: Add the TablePlus repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/tableplus.asc] https://deb.tableplus.com/debian/22 tableplus main

- name: Install graphical apps
  apt:
    name:
      - firefox
      - firefox-locale-fr
      - google-chrome-stable
      - gimp
      - inkscape
      - vlc
      - apt-transport-https
      - code
      - sublime-text
      - typora
      - tableplus

- name: Install dev tools
  apt:
    name:
      - yarn
      - python3
      - python3-pip
      - python-is-python3
      - btop
      - logrotate
      - mysql-client
      - terminator
    install_recommends: no

- name: Install lazygit
  unarchive:
    src: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_0.40.2_Linux_x86_64.tar.gz"
    remote_src: yes
    dest: /usr/local/bin

- name: Flush handlers
  meta: flush_handlers
