---
- name: Install basic packages
  apt:
    name:
      - vim
      - git
      - curl
      - wget
      - net-tools
      - dnsutils
      - build-essential
      - php

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Add the Mozilla PPA repository
  apt_repository:
    repo: ppa:mozillateam/ppa

- name: Add the Google Chrome repository
  block:
    - get_url:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        dest: /etc/apt/keyrings/chrome.asc
    - apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/chrome.asc] http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome

- name: Add the Microsoft repository
  block:
    - get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/keyrings/microsoft.asc
    - apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main
        filename: vscode

- name: Add the Inkscape PPA repository
  apt_repository:
    repo: ppa:inkscape.dev/stable

- name: Add the Sublime text repository
  block:
    - get_url:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        dest: /etc/apt/keyrings/sublime.asc
    - apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/sublime.asc] https://download.sublimetext.com/ apt/stable/
        filename: sublime-text

- name: Add the Typora repository
  block:
    - get_url:
        url: https://typoraio.cn/linux/public-key.asc
        dest: /etc/apt/keyrings/typora.asc
    - apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/typora.asc] https://typora.io/linux ./
        filename: typora

- name: Install graphical apps
  apt:
    name:
      - firefox
      - firefox-locale-fr
      - google-chrome-stable
      - gimp
      - inkscape
      - vlc
      - apt-transport-https
      - code
      - sublime-text
      - typora
